export default {
  cast: [
    {
      adult: false,
      gender: 2,
      id: 4886,
      known_for_department: "Acting",
      name: "Norman Reedus",
      original_name: "Norman Reedus",
      popularity: 14.168,
      profile_path: "/x0VtaRWYKPEegZJv7cxqKtB9k98.jpg",
      roles: [
        {
          credit_id: "5256cb3919c2956ff605e052",
          character: "Daryl Dixon",
          episode_count: 161,
        },
      ],
      total_episode_count: 161,
      order: 0,
    },
    {
      adult: false,
      gender: 1,
      id: 31535,
      known_for_department: "Acting",
      name: "Melissa McBride",
      original_name: "Melissa McBride",
      popularity: 5.905,
      profile_path: "/a1yjfKwaLbSpgzOfDdnNk2nxaQx.jpg",
      roles: [
        {
          credit_id: "5256cb3919c2956ff605e166",
          character: "Carol Peletier",
          episode_count: 161,
        },
      ],
      total_episode_count: 161,
      order: 1,
    },
    {
      adult: false,
      gender: 1,
      id: 62220,
      known_for_department: "Acting",
      name: "Lauren Cohan",
      original_name: "Lauren Cohan",
      popularity: 15.692,
      profile_path: "/zJ9nZ5jqQTUD55GLKbgfiKlUoBN.jpg",
      roles: [
        {
          credit_id: "5256cb3919c2956ff605e0e0",
          character: "Maggie Greene",
          episode_count: 154,
        },
      ],
      total_episode_count: 154,
      order: 2,
    },
    {
      adult: false,
      gender: 1,
      id: 82104,
      known_for_department: "Acting",
      name: "Danai Gurira",
      original_name: "Danai Gurira",
      popularity: 6.213,
      profile_path: "/z7H7QeQvr24vskGlANQhG43vozQ.jpg",
      roles: [
        {
          credit_id: "5256cb3b19c2956ff605e2c4",
          character: "Michonne",
          episode_count: 134,
        },
      ],
      total_episode_count: 134,
      order: 1,
    },
    {
      adult: false,
      gender: 2,
      id: 7062,
      known_for_department: "Acting",
      name: "Andrew Lincoln",
      original_name: "Andrew Lincoln",
      popularity: 6.104,
      profile_path: "/bu1uBQM6ODGRE5TEm6l8gmyOApn.jpg",
      roles: [
        {
          credit_id: "5256cb3819c2956ff605df9c",
          character: "Rick Grimes",
          episode_count: 131,
        },
      ],
      total_episode_count: 131,
      order: 0,
    },
    {
      adult: false,
      gender: 2,
      id: 215056,
      known_for_department: "Acting",
      name: "Chandler Riggs",
      original_name: "Chandler Riggs",
      popularity: 4.821,
      profile_path: "/w7LGO0SdH2w1vey52yksohI0BqQ.jpg",
      roles: [
        {
          credit_id: "5256cb3919c2956ff605dfea",
          character: "Carl Grimes",
          episode_count: 115,
        },
      ],
      total_episode_count: 115,
      order: 4,
    },
    {
      adult: false,
      gender: 1,
      id: 84224,
      known_for_department: "Acting",
      name: "Christian Serratos",
      original_name: "Christian Serratos",
      popularity: 6.478,
      profile_path: "/3odIVQPRdJ0aNuecrtciodBi0rL.jpg",
      roles: [
        {
          credit_id: "53392aadc3a3680e760057ab",
          character: "Rosita Espinosa",
          episode_count: 108,
        },
      ],
      total_episode_count: 108,
      order: 3,
    },
    {
      adult: false,
      gender: 2,
      id: 1252310,
      known_for_department: "Acting",
      name: "Josh McDermitt",
      original_name: "Josh McDermitt",
      popularity: 4.504,
      profile_path: "/ueZwswzCiJ0KgLNCKnrBNQvl0aE.jpg",
      roles: [
        {
          credit_id: "53392a9c9251417da10041c8",
          character: "Eugene Porter",
          episode_count: 105,
        },
      ],
      total_episode_count: 105,
      order: 4,
    },
    {
      adult: false,
      gender: 2,
      id: 215055,
      known_for_department: "Acting",
      name: "Steven Yeun",
      original_name: "Steven Yeun",
      popularity: 8.597,
      profile_path: "/cnzyTmVMeyt9rIkR4bYFarAFEbD.jpg",
      roles: [
        {
          credit_id: "5256cb3919c2956ff605e0b2",
          character: "Glenn Rhee",
          episode_count: 99,
        },
      ],
      total_episode_count: 99,
      order: 1,
    },
    {
      adult: false,
      gender: 2,
      id: 41688,
      known_for_department: "Acting",
      name: "Seth Gilliam",
      original_name: "Seth Gilliam",
      popularity: 1.402,
      profile_path: "/uX4k1H9sRx3VDewQRuQO0oQrWEW.jpg",
      roles: [
        {
          credit_id: "57a9115dc3a368254e00ae2d",
          character: "Gabriel Stokes",
          episode_count: 90,
        },
      ],
      total_episode_count: 90,
      order: 5,
    },
    {
      adult: false,
      gender: 2,
      id: 555249,
      known_for_department: "Acting",
      name: "Ross Marquand",
      original_name: "Ross Marquand",
      popularity: 4.555,
      profile_path: "/jIGiAslF6KWcdHMV2sf4bETv72C.jpg",
      roles: [
        {
          credit_id: "5574d2c3c3a3686b7d0049c8",
          character: "Aaron",
          episode_count: 82,
        },
      ],
      total_episode_count: 82,
      order: 6,
    },
    {
      adult: false,
      gender: 1,
      id: 204031,
      known_for_department: "Acting",
      name: "Alanna Masterson",
      original_name: "Alanna Masterson",
      popularity: 7.899,
      profile_path: "/1tuyTwayZOcu81sYMzlmkLMMb1z.jpg",
      roles: [
        {
          credit_id: "53392a8c9251417dad004080",
          character: "Tara Chambler",
          episode_count: 75,
        },
      ],
      total_episode_count: 75,
      order: 265,
    },
    {
      adult: false,
      gender: 2,
      id: 47296,
      known_for_department: "Acting",
      name: "Jeffrey Dean Morgan",
      original_name: "Jeffrey Dean Morgan",
      popularity: 7.586,
      profile_path: "/V3zDGR4rvED9fG7ODv1ph1Q4z4.jpg",
      roles: [
        {
          credit_id: "60515d9e24b3330028a1e64f",
          character: "Negan",
          episode_count: 62,
        },
      ],
      total_episode_count: 62,
      order: 10,
    },
  ],
};
