export default {
  _id: "559cb1209251414206000bc2",
  air_date: "2016-01-25",
  episodes: [
    {
      air_date: "2016-01-25",
      episode_number: 1,
      crew: [
        {
          job: "Director",
          department: "Directing",
          credit_id: "55fdd18bc3a3681325001899",
          adult: false,
          gender: 2,
          id: 3950,
          known_for_department: "Writing",
          name: "Len Wiseman",
          original_name: "Len Wiseman",
          popularity: 2.537,
          profile_path: "/1OQxKQDItiG1vNwNBzDufLfBubA.jpg",
        },
        {
          job: "Writer",
          department: "Writing",
          credit_id: "56be72389251417347004d5f",
          adult: false,
          gender: 2,
          id: 1222585,
          known_for_department: "Production",
          name: "Tom Kapinos",
          original_name: "Tom Kapinos",
          popularity: 4.327,
          profile_path: "/ol7GfeO0OIDCWGYzlg1LDLmwluO.jpg",
        },
      ],
      guest_stars: [
        {
          character: "Delilah",
          credit_id: "55fdd3bcc3a3681337001848",
          order: 1,
          adult: false,
          gender: 1,
          id: 82662,
          known_for_department: "Acting",
          name: "AnnaLynne McCord",
          original_name: "AnnaLynne McCord",
          popularity: 4.654,
          profile_path: "/i3B4uESW39SgKXUt81xtpzQn2QW.jpg",
        },
        {
          character: "Jimmy Barnes",
          credit_id: "55fdd693c3a3681328001820",
          order: 3,
          adult: false,
          gender: 2,
          id: 59872,
          known_for_department: "Acting",
          name: "John Pankow",
          original_name: "John Pankow",
          popularity: 4.203,
          profile_path: "/cb4udknKU3v3nH0ej2NUzRJljXa.jpg",
        },
        {
          character: "Amanda",
          credit_id: "55fddc1c92514152a8001979",
          order: 4,
          adult: false,
          gender: 1,
          id: 109858,
          known_for_department: "Acting",
          name: "Kayla Ewell",
          original_name: "Kayla Ewell",
          popularity: 5.22,
          profile_path: "/erWiC1tRwFvPbj0KivUQk0Of9Xx.jpg",
        },
        {
          character: "Grey Cooper",
          credit_id: "55fddc6a92514152b40019e0",
          order: 5,
          adult: false,
          gender: 2,
          id: 104195,
          known_for_department: "Acting",
          name: "Bailey Chase",
          original_name: "Bailey Chase",
          popularity: 2.936,
          profile_path: "/1tqzsmbws2X225dIUK8sWze4bBR.jpg",
        },
        {
          character: "2Vile",
          credit_id: "56be710b9251417356004dfc",
          order: 11,
          adult: false,
          gender: 2,
          id: 1576541,
          known_for_department: "Acting",
          name: "Tomiwa Edun",
          original_name: "Tomiwa Edun",
          popularity: 2.313,
          profile_path: "/v6c64iaJWtUa4zkwvvo5msxvBlF.jpg",
        },
        {
          character: "Officer Diggs",
          credit_id: "56be716fc3a368180a005548",
          order: 12,
          adult: false,
          gender: 2,
          id: 111451,
          known_for_department: "Acting",
          name: "Matt Corboy",
          original_name: "Matt Corboy",
          popularity: 1.38,
          profile_path: "/hkyyIuwqN6AqLZj6YHUPfYa2EKF.jpg",
        },
        {
          character: "Young Band Boy",
          credit_id: "5ade9491c3a3686acf002b5c",
          order: 131,
          adult: false,
          gender: 2,
          id: 1031377,
          known_for_department: "Acting",
          name: "Chris Trousdale",
          original_name: "Chris Trousdale",
          popularity: 2.876,
          profile_path: "/sbKNKV85MbdnuM6lM2LXhDRtouD.jpg",
        },
        {
          character: "Butler",
          credit_id: "5ec6db88bd990c0020b51c85",
          order: 153,
          adult: false,
          gender: 2,
          id: 1555647,
          known_for_department: "Acting",
          name: "Jonathan Salisbury",
          original_name: "Jonathan Salisbury",
          popularity: 0.828,
          profile_path: "/2dhXKh3KuiMMlj9VsrpFbzAQ5FO.jpg",
        },
        {
          character: "Mean Girl",
          credit_id: "5ec6dba89979d20021389d30",
          order: 154,
          adult: false,
          gender: 1,
          id: 2647901,
          known_for_department: "Acting",
          name: "Leah Renee Benner",
          original_name: "Leah Renee Benner",
          popularity: 1.528,
          profile_path: "/4htBIjAVS3x6rYFjoBmCB9bfkMm.jpg",
        },
        {
          character: "2 Vile Crew #1",
          credit_id: "5ec6dcfc140bad001b1828f7",
          order: 155,
          adult: false,
          gender: 2,
          id: 1427673,
          known_for_department: "Acting",
          name: "Isaac Keys",
          original_name: "Isaac Keys",
          popularity: 0.84,
          profile_path: "/6t8QJG7rai1iTyjkxUrzOmsGIGu.jpg",
        },
        {
          character: "Traffic Cop",
          credit_id: "5ec6dddde635710022ce1cdc",
          order: 156,
          adult: false,
          gender: 2,
          id: 58950,
          known_for_department: "Acting",
          name: "Greg Collins",
          original_name: "Greg Collins",
          popularity: 2.195,
          profile_path: "/42p7hsOck2OzIkr4b9Wtp0HckkG.jpg",
        },
        {
          character: "Priest",
          credit_id: "5ec6dee86c849200212aaa83",
          order: 157,
          adult: false,
          gender: 2,
          id: 153946,
          known_for_department: "Acting",
          name: "Christopher Boyer",
          original_name: "Christopher Boyer",
          popularity: 1.287,
          profile_path: "/1QaPkKYDRwkSJVzdiUc0NXkpx12.jpg",
        },
        {
          character: "Cop #1",
          credit_id: "5ec6def9bd990c0020b51f48",
          order: 158,
          adult: false,
          gender: 2,
          id: 1497866,
          known_for_department: "Acting",
          name: "Andy Hoff",
          original_name: "Andy Hoff",
          popularity: 0.6,
          profile_path: "/i9HJpnlNrZO20qjEVRn2VChVuCx.jpg",
        },
        {
          character: "Valet",
          credit_id: "5ec6df07ae2811001f3c15ae",
          order: 159,
          adult: false,
          gender: 2,
          id: 1520061,
          known_for_department: "Acting",
          name: "Ty Chen",
          original_name: "Ty Chen",
          popularity: 0.631,
          profile_path: "/lJwLbfCaEVfxvCh4Ubyozj3Fiix.jpg",
        },
        {
          character: "Shooter",
          credit_id: "5ec6df1b0fb17f001c7a1024",
          order: 160,
          adult: false,
          gender: 2,
          id: 1464847,
          known_for_department: "Acting",
          name: "Jeff Staron",
          original_name: "Jeff Staron",
          popularity: 1.008,
          profile_path: "/nqFevaALj7WfnUP12blvpVNFqhY.jpg",
        },
        {
          character: "Bodyguard",
          credit_id: "5ec6df2785b1050022513c9f",
          order: 161,
          adult: false,
          gender: 2,
          id: 1694998,
          known_for_department: "Acting",
          name: "Lance Broadway",
          original_name: "Lance Broadway",
          popularity: 1.932,
          profile_path: "/jifKcNQXE43FPFgikwgzgZZhdEY.jpg",
        },
      ],
      id: 1130976,
      name: "Pilot",
      overview:
        "Upon leaving hell, Lucifer Morningstar retreats to Los Angeles for a more exciting life. When the murder of a friend connects him with LAPD detective Chloe Decker, Lucifer becomes intrigued with the idea of punishing criminals, sending the devil himself into a struggle between good and evil.",
      production_code: "276096",
      season_number: 1,
      still_path: "/aSl1ASgOlNkukh0kalKCvGKZeb4.jpg",
      vote_average: 7.5,
      vote_count: 72,
    },
    {
      air_date: "2016-02-01",
      episode_number: 2,
      crew: [
        {
          job: "Director",
          department: "Directing",
          credit_id: "56be64919251417344004abb",
          adult: false,
          gender: 2,
          id: 11817,
          known_for_department: "Directing",
          name: "Nathan Hope",
          original_name: "Nathan Hope",
          popularity: 2.088,
          profile_path: null,
        },
        {
          job: "Executive Consultant",
          department: "Production",
          credit_id: "56be6e7292514140a6002dbf",
          adult: false,
          gender: 2,
          id: 1222585,
          known_for_department: "Production",
          name: "Tom Kapinos",
          original_name: "Tom Kapinos",
          popularity: 4.327,
          profile_path: "/ol7GfeO0OIDCWGYzlg1LDLmwluO.jpg",
        },
        {
          job: "Music",
          department: "Sound",
          credit_id: "56be6e8b925141734d004de4",
          adult: false,
          gender: 2,
          id: 7229,
          known_for_department: "Sound",
          name: "Marco Beltrami",
          original_name: "Marco Beltrami",
          popularity: 1.157,
          profile_path: "/fb3TfFITlOC0BN3kNpUXj1FL0LN.jpg",
        },
        {
          job: "Music",
          department: "Sound",
          credit_id: "56be6ed6925141734d004de8",
          adult: false,
          gender: 2,
          id: 64281,
          known_for_department: "Sound",
          name: "Dennis Smith",
          original_name: "Dennis Smith",
          popularity: 0.608,
          profile_path: "/ky5H2kqat3CbzBnpA5X1HhQfCFi.jpg",
        },
        {
          job: "Writer",
          department: "Writing",
          credit_id: "56be64789251417356004c46",
          adult: false,
          gender: 2,
          id: 1248201,
          known_for_department: "Writing",
          name: "Joe Henderson",
          original_name: "Joe Henderson",
          popularity: 1.96,
          profile_path: null,
        },
        {
          job: "Executive Producer",
          department: "Production",
          credit_id: "55fdca6692514152b4001806",
          adult: false,
          gender: 2,
          id: 770,
          known_for_department: "Production",
          name: "Jerry Bruckheimer",
          original_name: "Jerry Bruckheimer",
          popularity: 2.092,
          profile_path: "/vTKQVRrj9vOrKLkPEsXHxmpV9c3.jpg",
        },
        {
          job: "Art Direction",
          department: "Art",
          credit_id: "580229399251415da20015b2",
          adult: false,
          gender: 0,
          id: 1391672,
          known_for_department: "Art",
          name: "Peter Ochotta",
          original_name: "Peter Ochotta",
          popularity: 0.982,
          profile_path: null,
        },
        {
          job: "Hair Department Head",
          department: "Costume & Make-Up",
          credit_id: "5802296f9251417c31000bfa",
          adult: false,
          gender: 0,
          id: 1302179,
          known_for_department: "Costume & Make-Up",
          name: "Gina Sherritt",
          original_name: "Gina Sherritt",
          popularity: 0.6,
          profile_path: null,
        },
        {
          job: "Makeup Department Head",
          department: "Costume & Make-Up",
          credit_id: "58022979c3a3684d490018ce",
          adult: false,
          gender: 0,
          id: 1515597,
          known_for_department: "Costume & Make-Up",
          name: "Jennifer Kipps",
          original_name: "Jennifer Kipps",
          popularity: 0.6,
          profile_path: null,
        },
        {
          job: "Property Master",
          department: "Crew",
          credit_id: "580229909251417c90000be8",
          adult: false,
          gender: 2,
          id: 1694850,
          known_for_department: "Art",
          name: "Ben Krakowsky",
          original_name: "Ben Krakowsky",
          popularity: 0.6,
          profile_path: null,
        },
        {
          job: "Music Supervisor",
          department: "Sound",
          credit_id: "580229bdc3a36879bb000ad2",
          adult: false,
          gender: 1,
          id: 1538148,
          known_for_department: "Sound",
          name: "Alexandra Patsavas",
          original_name: "Alexandra Patsavas",
          popularity: 0.645,
          profile_path: null,
        },
        {
          job: "Music Editor",
          department: "Sound",
          credit_id: "580229c7c3a368549e0015b5",
          adult: false,
          gender: 2,
          id: 1408706,
          known_for_department: "Sound",
          name: "Chris McGeary",
          original_name: "Chris McGeary",
          popularity: 1.567,
          profile_path: "/8m9DqQoNjbghXuVnCTrR7aqEpM6.jpg",
        },
        {
          job: "Casting",
          department: "Production",
          credit_id: "58023b15c3a36877fd001601",
          adult: false,
          gender: 1,
          id: 41676,
          known_for_department: "Production",
          name: "Rebecca Mangieri",
          original_name: "Rebecca Mangieri",
          popularity: 0.714,
          profile_path: null,
        },
        {
          job: "Casting",
          department: "Production",
          credit_id: "58023b2d9251417c56001890",
          adult: false,
          gender: 1,
          id: 41677,
          known_for_department: "Production",
          name: "Wendy Weidman",
          original_name: "Wendy Weidman",
          popularity: 1.614,
          profile_path: null,
        },
        {
          job: "Casting",
          department: "Production",
          credit_id: "58023bfbc3a36877fd0016c3",
          adult: false,
          gender: 1,
          id: 986277,
          known_for_department: "Production",
          name: "Corinne Clark",
          original_name: "Corinne Clark",
          popularity: 1.216,
          profile_path: "/vdlaA6UP9Hi7iKBU7CAYl6joeRA.jpg",
        },
        {
          job: "Casting",
          department: "Production",
          credit_id: "58023c169251417a33001909",
          adult: false,
          gender: 1,
          id: 1122003,
          known_for_department: "Production",
          name: "Jennifer Page",
          original_name: "Jennifer Page",
          popularity: 1.67,
          profile_path: null,
        },
        {
          job: "Co-Producer",
          department: "Production",
          credit_id: "5f33288cef8b320037122199",
          adult: false,
          gender: 0,
          id: 1576538,
          known_for_department: "Production",
          name: "Jonathan Brody",
          original_name: "Jonathan Brody",
          popularity: 1.614,
          profile_path: null,
        },
        {
          job: "Executive Story Editor",
          department: "Writing",
          credit_id: "5f3328e98a88b200359dc86c",
          adult: false,
          gender: 0,
          id: 1407158,
          known_for_department: "Writing",
          name: "Jenn Kao",
          original_name: "Jenn Kao",
          popularity: 0.6,
          profile_path: null,
        },
        {
          job: "Production Manager",
          department: "Production",
          credit_id: "5f332954ef8b3200371222f8",
          adult: false,
          gender: 0,
          id: 1825921,
          known_for_department: "Production",
          name: "Bonnie Benwick",
          original_name: "Bonnie Benwick",
          popularity: 0.6,
          profile_path: null,
        },
        {
          job: "First Assistant Director",
          department: "Directing",
          credit_id: "5f332975ef8b320039120b72",
          adult: false,
          gender: 2,
          id: 1830340,
          known_for_department: "Directing",
          name: "Mick MacKay",
          original_name: "Mick MacKay",
          popularity: 1.4,
          profile_path: null,
        },
        {
          job: "Second Assistant Director",
          department: "Directing",
          credit_id: "5f3329aca3e4ba0032ccac41",
          adult: false,
          gender: 1,
          id: 2109694,
          known_for_department: "Directing",
          name: "Marijke Richman",
          original_name: "Marijke Richman",
          popularity: 0.6,
          profile_path: null,
        },
        {
          job: "Casting Associate",
          department: "Production",
          credit_id: "5f332a16e10f460037a8a5fb",
          adult: false,
          gender: 0,
          id: 2739024,
          known_for_department: "Production",
          name: "Emily Schoener",
          original_name: "Emily Schoener",
          popularity: 0.6,
          profile_path: null,
        },
        {
          job: "Casting",
          department: "Production",
          credit_id: "5f332a8d29c62600345bdea1",
          adult: false,
          gender: 0,
          id: 63532,
          known_for_department: "Production",
          name: "Elizabeth Barnes",
          original_name: "Elizabeth Barnes",
          popularity: 0.6,
          profile_path: null,
        },
        {
          job: "Casting",
          department: "Production",
          credit_id: "5f332aa1e10f460036a8a61c",
          adult: false,
          gender: 0,
          id: 60226,
          known_for_department: "Production",
          name: "Corbin Bronson",
          original_name: "Corbin Bronson",
          popularity: 0.6,
          profile_path: null,
        },
        {
          job: "Set Decoration",
          department: "Art",
          credit_id: "5f332b1f8a88b200349db48d",
          adult: false,
          gender: 0,
          id: 63557,
          known_for_department: "Art",
          name: "Erik Gerlund",
          original_name: "Erik Gerlund",
          popularity: 0.98,
          profile_path: null,
        },
        {
          job: "Costume Designer",
          department: "Costume & Make-Up",
          credit_id: "5f332b45a3e4ba0034cca74d",
          adult: false,
          gender: 0,
          id: 1584106,
          known_for_department: "Costume & Make-Up",
          name: "Shanna Mair",
          original_name: "Shanna Mair",
          popularity: 0.6,
          profile_path: null,
        },
        {
          job: "Location Manager",
          department: "Production",
          credit_id: "5f332c0def8b32003612027a",
          adult: false,
          gender: 0,
          id: 1440923,
          known_for_department: "Production",
          name: "Tracey Renyard",
          original_name: "Tracey Renyard",
          popularity: 0.6,
          profile_path: null,
        },
        {
          job: "Stunt Coordinator",
          department: "Crew",
          credit_id: "5f332c1e8a88b200369da525",
          adult: false,
          gender: 2,
          id: 184842,
          known_for_department: "Acting",
          name: "Rob Hayter",
          original_name: "Rob Hayter",
          popularity: 0.996,
          profile_path: "/fUwCX0GPVHsPhBbMkKj3ajWtSug.jpg",
        },
        {
          job: "Key Grip",
          department: "Camera",
          credit_id: "5f332c81ef8b3200361202b8",
          adult: false,
          gender: 0,
          id: 1792215,
          known_for_department: "Acting",
          name: "Vincent Phillips",
          original_name: "Vincent Phillips",
          popularity: 0.6,
          profile_path: null,
        },
        {
          job: "Gaffer",
          department: "Lighting",
          credit_id: "5f332c9ee10f460034a8c3f4",
          adult: false,
          gender: 0,
          id: 1613992,
          known_for_department: "Lighting",
          name: "Sean Rooney",
          original_name: "Sean Rooney",
          popularity: 0.6,
          profile_path: null,
        },
        {
          job: "Construction Coordinator",
          department: "Art",
          credit_id: "5f332cd529c62600365c0231",
          adult: false,
          gender: 0,
          id: 2485454,
          known_for_department: "Costume & Make-Up",
          name: "Michael Bevis",
          original_name: "Michael Bevis",
          popularity: 0.84,
          profile_path: null,
        },
        {
          job: "Production Accountant",
          department: "Production",
          credit_id: "5f332d0529c62600365c0291",
          adult: false,
          gender: 0,
          id: 1514174,
          known_for_department: "Production",
          name: "Lindsay Moffat",
          original_name: "Lindsay Moffat",
          popularity: 0.6,
          profile_path: null,
        },
        {
          job: "Production Coordinator",
          department: "Production",
          credit_id: "5f332d300582240034aab14e",
          adult: false,
          gender: 0,
          id: 2091589,
          known_for_department: "Production",
          name: "Kimberly Buckham",
          original_name: "Kimberly Buckham",
          popularity: 0.828,
          profile_path: null,
        },
        {
          job: "Production Sound Mixer",
          department: "Sound",
          credit_id: "5f332d598a88b200339db86b",
          adult: false,
          gender: 0,
          id: 2739037,
          known_for_department: "Sound",
          name: "Graig Stauffer",
          original_name: "Graig Stauffer",
          popularity: 0.6,
          profile_path: null,
        },
        {
          job: "Supervising Sound Editor",
          department: "Sound",
          credit_id: "5f332dbca3e4ba0033ccdd89",
          adult: false,
          gender: 0,
          id: 1538123,
          known_for_department: "Sound",
          name: "Eileen Horta",
          original_name: "Eileen Horta",
          popularity: 0.6,
          profile_path: null,
        },
      ],
      guest_stars: [
        {
          character: "Jimmy Barnes",
          credit_id: "55fdd693c3a3681328001820",
          order: 3,
          adult: false,
          gender: 2,
          id: 59872,
          known_for_department: "Acting",
          name: "John Pankow",
          original_name: "John Pankow",
          popularity: 4.203,
          profile_path: "/cb4udknKU3v3nH0ej2NUzRJljXa.jpg",
        },
        {
          character: "Nick Hofmeister",
          credit_id: "56be5fbe925141734d004be8",
          order: 7,
          adult: false,
          gender: 2,
          id: 4654,
          known_for_department: "Acting",
          name: "Jeremy Davies",
          original_name: "Jeremy Davies",
          popularity: 5.49,
          profile_path: "/b15bF582QuQjyw2Jgr5wxErWrDM.jpg",
        },
        {
          character: "Josh Bryant",
          credit_id: "56be602d9251417359004c4c",
          order: 8,
          adult: false,
          gender: 2,
          id: 52037,
          known_for_department: "Acting",
          name: "Robert Ri'chard",
          original_name: "Robert Ri'chard",
          popularity: 2.832,
          profile_path: "/36cxvHbHtvl476v8lrqY7Cv3Jm7.jpg",
        },
        {
          character: "Street Preacher",
          credit_id: "56be6057c3a368180a0052ab",
          order: 9,
          adult: false,
          gender: 2,
          id: 169349,
          known_for_department: "Acting",
          name: "Evan Arnold",
          original_name: "Evan Arnold",
          popularity: 1.661,
          profile_path: "/meFpF2hqoODL1TMNgx1MNqUWiC1.jpg",
        },
        {
          character: "Mr. Russell",
          credit_id: "56be60db9251417356004be5",
          order: 10,
          adult: false,
          gender: 2,
          id: 102729,
          known_for_department: "Acting",
          name: "Greg Vaughan",
          original_name: "Greg Vaughan",
          popularity: 3.863,
          profile_path: "/nEQaofICWnNxXNjFnCUyTJD6rMg.jpg",
        },
        {
          character: "Robbie Russell Jr.",
          credit_id: "5a84420c9251410b4d00a94e",
          order: 102,
          adult: false,
          gender: 0,
          id: 1647683,
          known_for_department: "Acting",
          name: "Brady Roberts",
          original_name: "Brady Roberts",
          popularity: 0.6,
          profile_path: "/maJ0tv1vm0c9SGQhWemMNPOE6L1.jpg",
        },
        {
          character: "Bald Paparazzo",
          credit_id: "5ec6e21f85b1050020514979",
          order: 162,
          adult: false,
          gender: 0,
          id: 1366704,
          known_for_department: "Acting",
          name: "Danny Dworkis",
          original_name: "Danny Dworkis",
          popularity: 1.142,
          profile_path: "/kfbkBEYZzVtH2XzQNhfahVYyIAR.jpg",
        },
        {
          character: "Doctor",
          credit_id: "5ec6e240d2147c0023be0d48",
          order: 163,
          adult: false,
          gender: 1,
          id: 62716,
          known_for_department: "Acting",
          name: "B. J. Harrison",
          original_name: "B. J. Harrison",
          popularity: 4.79,
          profile_path: "/wKQzk78i0nCdSASDFwma0z1tZsv.jpg",
        },
        {
          character: "Irate Woman",
          credit_id: "5ec6e6da9979d2002138a66e",
          order: 164,
          adult: false,
          gender: 1,
          id: 2543758,
          known_for_department: "Acting",
          name: "Jenna Hastings",
          original_name: "Jenna Hastings",
          popularity: 0.98,
          profile_path: "/zSc3mA9I3ebObNjseUThevc4rKp.jpg",
        },
        {
          character: "Sweaty Paparazzo",
          credit_id: "5ec6ec9d9979d20020314098",
          order: 165,
          adult: false,
          gender: 2,
          id: 143333,
          known_for_department: "Acting",
          name: "Marcus Hondro",
          original_name: "Marcus Hondro",
          popularity: 1.428,
          profile_path: "/1PjH36pZQinPACQxyia359F8YPW.jpg",
        },
        {
          character: "Handsome Man",
          credit_id: "5ec6ecbe0fb17f001d7b125d",
          order: 166,
          adult: false,
          gender: 2,
          id: 1558027,
          known_for_department: "Acting",
          name: "Andres Joseph",
          original_name: "Andres Joseph",
          popularity: 0.762,
          profile_path: "/oqVXsqI6vUgl2qaJgtR4ZOtbrgG.jpg",
        },
        {
          character: "Tall Paparazzo",
          credit_id: "5ec6ecef5a5ed0002044337d",
          order: 167,
          adult: false,
          gender: 2,
          id: 2647970,
          known_for_department: "Acting",
          name: "Rema Kibayi",
          original_name: "Rema Kibayi",
          popularity: 1.094,
          profile_path: "/iDsLo7ku0A2qepLcigIFLEFwEkX.jpg",
        },
        {
          character: "Young Woman",
          credit_id: "5ec6edb2e635710020cd0fc9",
          order: 168,
          adult: false,
          gender: 1,
          id: 1191706,
          known_for_department: "Crew",
          name: "Crystal Mudry",
          original_name: "Crystal Mudry",
          popularity: 1.96,
          profile_path: "/z5Zp4GbPtWuEbl7rECRehcHxGFG.jpg",
        },
        {
          character: "Desk Cop",
          credit_id: "5ec6edd75a5ed0001f43c666",
          order: 169,
          adult: false,
          gender: 1,
          id: 1881528,
          known_for_department: "Acting",
          name: "Lissa Neptuno",
          original_name: "Lissa Neptuno",
          popularity: 2.007,
          profile_path: "/x1IOyR0S9dhkoDjScQAMjB576Ts.jpg",
        },
        {
          character: "Beautiful Woman",
          credit_id: "5ec6ee876c8492001f298eb3",
          order: 170,
          adult: false,
          gender: 1,
          id: 1997524,
          known_for_department: "Acting",
          name: "Fei Ren",
          original_name: "Fei Ren",
          popularity: 1.429,
          profile_path: "/8NUW3avyqDhSml9F36wKZNsu4NB.jpg",
        },
        {
          character: "Stern Female Desk Cop",
          credit_id: "5ec6eec60fb17f001b7a9bde",
          order: 171,
          adult: false,
          gender: 1,
          id: 64243,
          known_for_department: "Acting",
          name: "Livia Treviño",
          original_name: "Livia Treviño",
          popularity: 3.006,
          profile_path: "/9HXrvSKjTM2suqNFIXexmDYc1o4.jpg",
        },
      ],
      id: 1160783,
      name: "Lucifer, Stay. Good Devil.",
      overview:
        "When a movie star's son is killed after being chased by the paparazzi, Chloe takes a deep look into the case with a little help from Lucifer. Meanwhile, Maze and Amenadiel continue to encourage Lucifer to go back to hell.",
      production_code: "4X6502",
      season_number: 1,
      still_path: "/ck8mSXXijr8xIXNqn2hbx4b2HKj.jpg",
      vote_average: 7.5,
      vote_count: 50,
    },
    {
      air_date: "2016-02-08",
      episode_number: 3,
      crew: [
        {
          job: "Director",
          department: "Directing",
          credit_id: "56c0b6bdc3a368180a00d49f",
          adult: false,
          gender: 2,
          id: 1224408,
          known_for_department: "Directing",
          name: "Louis Shaw Milito",
          original_name: "Louis Shaw Milito",
          popularity: 1.258,
          profile_path: null,
        },
        {
          job: "Writer",
          department: "Writing",
          credit_id: "56c0b6a2c3a368180a00d499",
          adult: false,
          gender: 2,
          id: 207074,
          known_for_department: "Writing",
          name: "Jason Ning",
          original_name: "Jason Ning",
          popularity: 0.652,
          profile_path: null,
        },
        {
          job: "Writer",
          department: "Writing",
          credit_id: "56c0b6abc3a36817fd00be48",
          adult: false,
          gender: 0,
          id: 1407158,
          known_for_department: "Writing",
          name: "Jenn Kao",
          original_name: "Jenn Kao",
          popularity: 0.6,
          profile_path: null,
        },
      ],
      guest_stars: [
        {
          character: "Debra",
          credit_id: "56bfb3c4c3a36817f2009ea6",
          order: 13,
          adult: false,
          gender: 1,
          id: 95039,
          known_for_department: "Acting",
          name: "Sofia Vassilieva",
          original_name: "Sofia Vassilieva",
          popularity: 5.136,
          profile_path: "/ryZqVhzjKfUBYuPMKXvZ1KF4tmU.jpg",
        },
        {
          character: "Ty Huntley",
          credit_id: "56bfb3e9c3a36817ef009f8b",
          order: 15,
          adult: false,
          gender: 2,
          id: 1115963,
          known_for_department: "Acting",
          name: "Redaric Williams",
          original_name: "Redaric Williams",
          popularity: 1.96,
          profile_path: "/aYORomrC2bXUqLi2vqrR8CTsU5T.jpg",
        },
        {
          character: "Ali Thornton",
          credit_id: "56bfb3fc92514169fd000b52",
          order: 16,
          adult: false,
          gender: 0,
          id: 1368791,
          known_for_department: "Acting",
          name: "Bri Neal",
          original_name: "Bri Neal",
          popularity: 4.678,
          profile_path: "/y70unu8k6oWVgvs833pxFds9Qa2.jpg",
        },
        {
          character: "Ronnie Hillman",
          credit_id: "56bfb40e92514169fd000b57",
          order: 17,
          adult: false,
          gender: 1,
          id: 58006,
          known_for_department: "Acting",
          name: "Jodi Lyn O'Keefe",
          original_name: "Jodi Lyn O'Keefe",
          popularity: 18.857,
          profile_path: "/5F9ESeRIlPrUbUcSYRvmNv6uPFU.jpg",
        },
        {
          character: "Lucibro",
          credit_id: "56bfb4939251414ba9001149",
          order: 18,
          adult: false,
          gender: 2,
          id: 1058027,
          known_for_department: "Acting",
          name: "Grant Harvey",
          original_name: "Grant Harvey",
          popularity: 2.663,
          profile_path: "/sThJJbhgjQOZNvCkHVO0g3qy78j.jpg",
        },
        {
          character: "Joe Hanson",
          credit_id: "56c0b5b692514105da000078",
          order: 19,
          adult: false,
          gender: 2,
          id: 55755,
          known_for_department: "Acting",
          name: "Richard T. Jones",
          original_name: "Richard T. Jones",
          popularity: 5.595,
          profile_path: "/hdko2C45Wr5G03Z8JwGjWMynP84.jpg",
        },
        {
          character: "Coroner",
          credit_id: "57e09b32925141045c00185f",
          order: 58,
          adult: false,
          gender: 2,
          id: 997197,
          known_for_department: "Acting",
          name: "Nelson Wong",
          original_name: "Nelson Wong",
          popularity: 1.752,
          profile_path: "/kepIOIAtrCZBvw7TuFufyGqQoo5.jpg",
        },
        {
          character: "Young Woman",
          credit_id: "5ec6f023d2147c0022b968c3",
          order: 172,
          adult: false,
          gender: 0,
          id: 1569748,
          known_for_department: "Acting",
          name: "Nicole Major",
          original_name: "Nicole Major",
          popularity: 0.6,
          profile_path: "/wT5jdaDcpEyZXeqqEftZY7VFArM.jpg",
        },
        {
          character: "Receptionist",
          credit_id: "5ec6f04b5a5ed0002044374a",
          order: 173,
          adult: false,
          gender: 1,
          id: 1085644,
          known_for_department: "Acting",
          name: "Aadila Dosani",
          original_name: "Aadila Dosani",
          popularity: 1.96,
          profile_path: "/plDJGrCm0tuoJQcDnGvYVIaZrNA.jpg",
        },
        {
          character: "Barfing Girl",
          credit_id: "5ec6f151d2147c0023be1c90",
          order: 174,
          adult: false,
          gender: 1,
          id: 2308418,
          known_for_department: "Acting",
          name: "Marika Sila",
          original_name: "Marika Sila",
          popularity: 1.788,
          profile_path: "/vwTCuw8a90RYIHer40cHVYoEDDZ.jpg",
        },
        {
          character: "Name Dropper Guy",
          credit_id: "5ec6f1cb140bad001b18358c",
          order: 175,
          adult: false,
          gender: 2,
          id: 1442429,
          known_for_department: "Acting",
          name: "Aatash Amir",
          original_name: "Aatash Amir",
          popularity: 0.634,
          profile_path: "/xlsq1aIzSEbScvRUxBdfy6E40VD.jpg",
        },
        {
          character: "Bomb Squad Tech",
          credit_id: "5ec6f1ebae2811001e3b6fb6",
          order: 176,
          adult: false,
          gender: 2,
          id: 2103775,
          known_for_department: "Acting",
          name: "Paul Almeida",
          original_name: "Paul Almeida",
          popularity: 0.828,
          profile_path: "/jBdE6c8GqKBVZiESIDDFj99jSHv.jpg",
        },
        {
          character: "UNI Cop",
          credit_id: "5ec6f2685a5ed0001f43c8ed",
          order: 177,
          adult: false,
          gender: 2,
          id: 1475789,
          known_for_department: "Acting",
          name: "Artin John",
          original_name: "Artin John",
          popularity: 2.719,
          profile_path: "/kxGjzPRsCvi5q1ykCSndTYHD4ZL.jpg",
        },
      ],
      id: 1160784,
      name: "The Would-Be Prince of Darkness",
      overview:
        "When a 22-year-old future superstar quarterback wakes up to find a dead girl floating in his swimming pool, he turns to his friend, Lucifer, for help. Lucifer enlists Chloe to investigate the case, which leads to the world of big money sports and people who will literally kill to be number one.",
      production_code: "4X6510",
      season_number: 1,
      still_path: "/eTRQGrNXhg3t1Z3dhNLOsGxomxm.jpg",
      vote_average: 7.5,
      vote_count: 40,
    },
    {
      air_date: "2016-02-15",
      episode_number: 4,
      crew: [
        {
          job: "Director",
          department: "Directing",
          credit_id: "56f16d7a92514165c0000035",
          adult: false,
          gender: 2,
          id: 173957,
          known_for_department: "Directing",
          name: "Matt Earl Beesley",
          original_name: "Matt Earl Beesley",
          popularity: 2.066,
          profile_path: null,
        },
        {
          job: "Writer",
          department: "Writing",
          credit_id: "56f16d58c3a36850a700002b",
          adult: false,
          gender: 1,
          id: 1222590,
          known_for_department: "Writing",
          name: "Ildy Modrovich",
          original_name: "Ildy Modrovich",
          popularity: 0.978,
          profile_path: null,
        },
      ],
      guest_stars: [
        {
          character: "Olivia Monroe",
          credit_id: "56f16c1992514144780004a5",
          order: 20,
          adult: false,
          gender: 1,
          id: 92614,
          known_for_department: "Acting",
          name: "Dawn Olivieri",
          original_name: "Dawn Olivieri",
          popularity: 6.972,
          profile_path: "/tet7ZVbzhLWwT44m9j94folyl5N.jpg",
        },
        {
          character: "Carver Cruz",
          credit_id: "56f16c5b92514165c0000001",
          order: 21,
          adult: false,
          gender: 2,
          id: 59238,
          known_for_department: "Acting",
          name: "Chris Marquette",
          original_name: "Chris Marquette",
          popularity: 5.245,
          profile_path: "/auJI59lLgNdjN8QcqmEywrYnW9C.jpg",
        },
        {
          character: "Lindsay Jolson",
          credit_id: "56f16c75c3a36850a0000008",
          order: 22,
          adult: false,
          gender: 1,
          id: 1242776,
          known_for_department: "Acting",
          name: "Bailey Noble",
          original_name: "Bailey Noble",
          popularity: 1.25,
          profile_path: "/83OOqpbafbMW0mTieXY30LNqJYD.jpg",
        },
        {
          character: "Kevin",
          credit_id: "56f16c9192514165be000005",
          order: 23,
          adult: false,
          gender: 2,
          id: 55464,
          known_for_department: "Acting",
          name: "Kelly Blatz",
          original_name: "Kelly Blatz",
          popularity: 1.144,
          profile_path: "/2PPGAQGFluZRHxdU8HPkEzM8Lvx.jpg",
        },
        {
          character: "Sad Sap",
          credit_id: "5ec6f5329979d2002138b441",
          order: 178,
          adult: false,
          gender: 0,
          id: 1368264,
          known_for_department: "Acting",
          name: "David Attar",
          original_name: "David Attar",
          popularity: 1.214,
          profile_path: "/r1RSGvChBmZXVXblcx41KRKcOYV.jpg",
        },
        {
          character: "Random Dude",
          credit_id: "5ec6f5cbe635710020cd14c5",
          order: 180,
          adult: false,
          gender: 0,
          id: 1579303,
          known_for_department: "Acting",
          name: "Guy Christie",
          original_name: "Guy Christie",
          popularity: 1.052,
          profile_path: "/S24ji8rTX250FZToqDLJSdJueW.jpg",
        },
        {
          character: "Buxom",
          credit_id: "5ec6f61d3d3557001ce89ffb",
          order: 181,
          adult: false,
          gender: 0,
          id: 1418251,
          known_for_department: "Acting",
          name: "Kirsten Comerford",
          original_name: "Kirsten Comerford",
          popularity: 2.143,
          profile_path: "/eqCe5c1fPJbbX7da5s4BgLhpFDX.jpg",
        },
        {
          character: "Security Guard",
          credit_id: "5ec6f6339979d200203144fa",
          order: 182,
          adult: false,
          gender: 2,
          id: 83445,
          known_for_department: "Acting",
          name: "Jason William Day",
          original_name: "Jason William Day",
          popularity: 1.73,
          profile_path: "/1KHyn8as1ZnAUR7uFnwy4YVvURZ.jpg",
        },
        {
          character: "George",
          credit_id: "5ec6f6516c849200202c094b",
          order: 183,
          adult: false,
          gender: 2,
          id: 1380498,
          known_for_department: "Acting",
          name: "Darcey Johnson",
          original_name: "Darcey Johnson",
          popularity: 1.22,
          profile_path: "/6OUGXS8X3YpvY0gC8oCYm39VFdq.jpg",
        },
        {
          character: "Gyrating Dude",
          credit_id: "5ec6f6f2ae2811001e3b74a5",
          order: 184,
          adult: false,
          gender: 2,
          id: 2556143,
          known_for_department: "Acting",
          name: "Sky Kao",
          original_name: "Sky Kao",
          popularity: 0.6,
          profile_path: "/tQ82RXHtSJTKjLYYEnDn6ie5Oz3.jpg",
        },
        {
          character: "Uniformed Officer",
          credit_id: "5ec7fcc9e635710020ce3b05",
          order: 691,
          adult: false,
          gender: 2,
          id: 1558026,
          known_for_department: "Acting",
          name: "Antonio Cayonne",
          original_name: "Antonio Cayonne",
          popularity: 1.932,
          profile_path: "/bCAxx1cNHsidOLwZys2FJEhsdrd.jpg",
        },
      ],
      id: 1160785,
      name: "Manly Whatnots",
      overview:
        "In an effort to get over his infatuation with Chloe, Lucifer decides that he must seduce her. Meanwhile the two team up on a missing girl case and Amenadiel confronts Maze about his concerns about Lucifer.",
      production_code: "4X6503",
      season_number: 1,
      still_path: "/jT6UcjnRP1MH8zUf0zL7NFGqhNQ.jpg",
      vote_average: 7.8,
      vote_count: 40,
    },
    {
      air_date: "2016-02-22",
      episode_number: 5,
      crew: [
        {
          job: "Director",
          department: "Directing",
          credit_id: "56f28528925141554f0012c4",
          adult: false,
          gender: 2,
          id: 21561,
          known_for_department: "Acting",
          name: "Tim Matheson",
          original_name: "Tim Matheson",
          popularity: 10.714,
          profile_path: "/trZ4QaDidCOPNy7HK9cYnmKHkg9.jpg",
        },
        {
          job: "Writer",
          department: "Writing",
          credit_id: "56f285139251415548001218",
          adult: false,
          gender: 1,
          id: 139853,
          known_for_department: "Writing",
          name: "Sheri Elwood",
          original_name: "Sheri Elwood",
          popularity: 1.22,
          profile_path: null,
        },
      ],
      guest_stars: [
        {
          character: "Olivia Monroe",
          credit_id: "56f16c1992514144780004a5",
          order: 20,
          adult: false,
          gender: 1,
          id: 92614,
          known_for_department: "Acting",
          name: "Dawn Olivieri",
          original_name: "Dawn Olivieri",
          popularity: 6.972,
          profile_path: "/tet7ZVbzhLWwT44m9j94folyl5N.jpg",
        },
        {
          character: "Benny Cho",
          credit_id: "56f16dfec3a36850ac00002b",
          order: 24,
          adult: false,
          gender: 2,
          id: 1215759,
          known_for_department: "Acting",
          name: "Eddie Shin",
          original_name: "Eddie Shin",
          popularity: 5.778,
          profile_path: "/sJQM9isg1IYedw6KYgPIE3l6xjc.jpg",
        },
        {
          character: "Yellow Viper",
          credit_id: "56f283a2c3a36807660014fb",
          order: 26,
          adult: false,
          gender: 0,
          id: 124495,
          known_for_department: "Acting",
          name: "Lanny Joon",
          original_name: "Lanny Joon",
          popularity: 2.22,
          profile_path: "/bIT1IKcrbp6gNBQPop4mJ69tWS9.jpg",
        },
        {
          character: "Dani Ramirez",
          credit_id: "56f2840a925141554f001297",
          order: 26,
          adult: false,
          gender: 1,
          id: 134180,
          known_for_department: "Acting",
          name: "Alyssa Diaz",
          original_name: "Alyssa Diaz",
          popularity: 13.37,
          profile_path: "/ihLNjM4E1Fjx5h4l8EL6r3iDRTa.jpg",
        },
        {
          character: "Diego Ramirez",
          credit_id: "56f28417925141553f00131c",
          order: 27,
          adult: false,
          gender: 2,
          id: 121825,
          known_for_department: "Acting",
          name: "Germaine De Leon",
          original_name: "Germaine De Leon",
          popularity: 1.62,
          profile_path: "/lfNbi77qHUYxyP5ut9wsLumWqdj.jpg",
        },
        {
          character: "Anthony Paolucci",
          credit_id: "56f28434c3a368077500125d",
          order: 28,
          adult: false,
          gender: 2,
          id: 58058,
          known_for_department: "Acting",
          name: "Lochlyn Munro",
          original_name: "Lochlyn Munro",
          popularity: 6.235,
          profile_path: "/bOJ03k0oe2R6snRgzV8M4Qtoo4O.jpg",
        },
        {
          character: "Hector",
          credit_id: "5ec6f84ce635710021cc280b",
          order: 185,
          adult: false,
          gender: 2,
          id: 1460719,
          known_for_department: "Acting",
          name: "Shaun Omaid",
          original_name: "Shaun Omaid",
          popularity: 1.79,
          profile_path: "/qttbi8RNm4wCNyymG7HcDmLRyVx.jpg",
        },
        {
          character: "Grizzled Uni Cop",
          credit_id: "5ec6f8635a5ed00020444167",
          order: 186,
          adult: false,
          gender: 0,
          id: 1366577,
          known_for_department: "Acting",
          name: "Howard Siegel",
          original_name: "Howard Siegel",
          popularity: 1.219,
          profile_path: "/wZMxlBaWDdI3El2nw12peOUkRig.jpg",
        },
        {
          character: "Mrs. Cortez",
          credit_id: "5ec6f8819979d2001f348ad2",
          order: 187,
          adult: false,
          gender: 1,
          id: 1475082,
          known_for_department: "Acting",
          name: "Gabriela Zimmerman",
          original_name: "Gabriela Zimmerman",
          popularity: 0.6,
          profile_path: "/mFLgc6qU7l0bYwLpfYll4UvrxKy.jpg",
        },
        {
          character: "Paola Cortez",
          credit_id: "5ec6f8963d3557001ce8a10f",
          order: 188,
          adult: false,
          gender: 1,
          id: 2648018,
          known_for_department: "Acting",
          name: "Paula Zerpa",
          original_name: "Paula Zerpa",
          popularity: 0.6,
          profile_path: "/deWjKWCbsMrOB09PpOsLrNBwXck.jpg",
        },
        {
          character: "Machete Model",
          credit_id: "5ec6f8ad5a5ed000204441c4",
          order: 189,
          adult: false,
          gender: 0,
          id: 1781890,
          known_for_department: "Acting",
          name: "Olena Medwid",
          original_name: "Olena Medwid",
          popularity: 1.78,
          profile_path: "/4G8WvmpExl1hkHYD1inKQlBQE2E.jpg",
        },
        {
          character: "Bartender",
          credit_id: "5ec6f925140bad001d19af0a",
          order: 191,
          adult: false,
          gender: 0,
          id: 1376357,
          known_for_department: "Acting",
          name: "Teresa Laverty",
          original_name: "Teresa Laverty",
          popularity: 0.6,
          profile_path: "/fOZz3cTHTCJ3s6pv6tpMCWZMAlR.jpg",
        },
        {
          character: "Barista",
          credit_id: "5ec6f9378e2e003dd611e5dd",
          order: 192,
          adult: false,
          gender: 1,
          id: 1366720,
          known_for_department: "Acting",
          name: "Pippa Mackie",
          original_name: "Pippa Mackie",
          popularity: 2.445,
          profile_path: "/vJ8kKchKkcBCweRUKXuELFSv5rF.jpg",
        },
        {
          character: "Cute Female Uni Cop",
          credit_id: "5ec6f90c0fb17f001d7b1d77",
          order: 467,
          adult: false,
          gender: 1,
          id: 2554153,
          known_for_department: "Acting",
          name: "Tori Katongo",
          original_name: "Tori Katongo",
          popularity: 1.63,
          profile_path: "/rZKjVHS7pqkcUmoPNgKbDwPFbqW.jpg",
        },
      ],
      id: 1160786,
      name: "Sweet Kicks",
      overview:
        "After a shooting occurs at a fashion show and a young woman is killed, Lucifer becomes intrigued by the danger of the situation and begs Chloe to get in on the case. Meanwhile, when Maze admits to Amenadiel that she wants to go back to hell, he sets his sights on Dr. Linda.",
      production_code: "4X6504",
      season_number: 1,
      still_path: "/nrRGeYit3Tvr2NocDmKEA5bH9sz.jpg",
      vote_average: 7.2,
      vote_count: 34,
    },
    {
      air_date: "2016-02-29",
      episode_number: 6,
      crew: [
        {
          job: "Director",
          department: "Directing",
          credit_id: "56f3c1419251411a8b002340",
          adult: false,
          gender: 2,
          id: 19839,
          known_for_department: "Acting",
          name: "David Paymer",
          original_name: "David Paymer",
          popularity: 6.565,
          profile_path: "/owoOdDFgXpls1OFKwmQ104Nkl5.jpg",
        },
        {
          job: "Writer",
          department: "Writing",
          credit_id: "56c0b6a2c3a368180a00d499",
          adult: false,
          gender: 2,
          id: 207074,
          known_for_department: "Writing",
          name: "Jason Ning",
          original_name: "Jason Ning",
          popularity: 0.652,
          profile_path: null,
        },
      ],
      guest_stars: [
        {
          character: "Hank Cutter",
          credit_id: "56f3bf8a925141769e001368",
          order: 29,
          adult: false,
          gender: 2,
          id: 3197,
          known_for_department: "Acting",
          name: "Tom Sizemore",
          original_name: "Tom Sizemore",
          popularity: 7.344,
          profile_path: "/soINOuacuiThRb2LyPD4tTWve7C.jpg",
        },
        {
          character: "Renny",
          credit_id: "56f3c02792514176c50013d3",
          order: 30,
          adult: false,
          gender: 2,
          id: 129985,
          known_for_department: "Acting",
          name: "Teach Grant",
          original_name: "Teach Grant",
          popularity: 3.335,
          profile_path: "/18UPpMgudrgvZlKE5HWcM80JKdS.jpg",
        },
        {
          character: "Frankie Costa",
          credit_id: "56f3c05cc3a3682fcf0026be",
          order: 31,
          adult: false,
          gender: 2,
          id: 154829,
          known_for_department: "Acting",
          name: "Craig Gellis",
          original_name: "Craig Gellis",
          popularity: 5.474,
          profile_path: "/khZP4LGKZiUqsP2I5IvCAQ5cYSF.jpg",
        },
        {
          character: "Coroner",
          credit_id: "57e09b32925141045c00185f",
          order: 58,
          adult: false,
          gender: 2,
          id: 997197,
          known_for_department: "Acting",
          name: "Nelson Wong",
          original_name: "Nelson Wong",
          popularity: 1.752,
          profile_path: "/kepIOIAtrCZBvw7TuFufyGqQoo5.jpg",
        },
        {
          character: "Erwin",
          credit_id: "5ec711926c849200202c30d1",
          order: 193,
          adult: false,
          gender: 2,
          id: 172825,
          known_for_department: "Acting",
          name: "Sean Tyson",
          original_name: "Sean Tyson",
          popularity: 1.96,
          profile_path: "/8W8RAuPhywkh1eglkOqwUDVzH47.jpg",
        },
        {
          character: "Police Officer",
          credit_id: "5ec7152eae2811001f3c4bdb",
          order: 196,
          adult: false,
          gender: 0,
          id: 1874345,
          known_for_department: "Acting",
          name: "Lee Shan Gibson",
          original_name: "Lee Shan Gibson",
          popularity: 1.4,
          profile_path: "/jU9lEXTYwgFScS9spsTn4izanyI.jpg",
        },
        {
          character: "Brittanie #2",
          credit_id: "5ec738bf8e2e0000201f4175",
          order: 732,
          adult: false,
          gender: 1,
          id: 1516211,
          known_for_department: "Acting",
          name: "Emily Maddison",
          original_name: "Emily Maddison",
          popularity: 4.532,
          profile_path: "/cGfJnsrslN75ju7Dpmv8NgyHDgI.jpg",
        },
        {
          character: "Brittanie #1",
          credit_id: "5ec7390e3d3557001ce8e5f6",
          order: 733,
          adult: false,
          gender: 1,
          id: 2648252,
          known_for_department: "Acting",
          name: "Tina Pham",
          original_name: "Tina Pham",
          popularity: 1.96,
          profile_path: "/sn7ycikKtANMU4TKJq98oHxNYpi.jpg",
        },
      ],
      id: 1160787,
      name: "Favorite Son",
      overview:
        "Lucifer bails on Chloe when he becomes bored with her investigation into a ruthless biker gang murder. However, when he discovers something was stolen during the crime that was very personal to him, he demands that Chloe let him rejoin the case.",
      production_code: "4X6505",
      season_number: 1,
      still_path: "/iCPIYG06s4rEUAffTI7D1xuVPvy.jpg",
      vote_average: 7.539,
      vote_count: 38,
    },
    {
      air_date: "2016-03-07",
      episode_number: 7,
      crew: [
        {
          job: "Director",
          department: "Directing",
          credit_id: "56f41108c3a3682fe60031e8",
          adult: false,
          gender: 2,
          id: 23628,
          known_for_department: "Acting",
          name: "Eriq La Salle",
          original_name: "Eriq La Salle",
          popularity: 11.006,
          profile_path: "/vFNYNLQyIoDtsSp3xQ2x1bs6Oud.jpg",
        },
        {
          job: "Writer",
          department: "Writing",
          credit_id: "56f41101925141769e001e90",
          adult: false,
          gender: 0,
          id: 1382168,
          known_for_department: "Writing",
          name: "Alex Katsnelson",
          original_name: "Alex Katsnelson",
          popularity: 1.22,
          profile_path: null,
        },
      ],
      guest_stars: [
        {
          character: "Anthony Paolucci",
          credit_id: "56f28434c3a368077500125d",
          order: 28,
          adult: false,
          gender: 2,
          id: 58058,
          known_for_department: "Acting",
          name: "Lochlyn Munro",
          original_name: "Lochlyn Munro",
          popularity: 6.235,
          profile_path: "/bOJ03k0oe2R6snRgzV8M4Qtoo4O.jpg",
        },
        {
          character: "Sergei",
          credit_id: "56f414259251411a8b002df1",
          order: 33,
          adult: false,
          gender: 2,
          id: 137750,
          known_for_department: "Acting",
          name: "Hal Ozsan",
          original_name: "Hal Ozsan",
          popularity: 5.441,
          profile_path: "/A7OwOraJuVNaCt4MHvslH5n6rK.jpg",
        },
        {
          character: "Carmen",
          credit_id: "56f414bac3a3682fd20031d2",
          order: 34,
          adult: false,
          gender: 2,
          id: 17490,
          known_for_department: "Acting",
          name: "Isiah Whitlock Jr.",
          original_name: "Isiah Whitlock Jr.",
          popularity: 2.184,
          profile_path: "/8OIhQb53rMX7VcTLZbAMeVd7tHc.jpg",
        },
        {
          character: "Agent Pitts",
          credit_id: "56f414f692514176c5001e93",
          order: 35,
          adult: false,
          gender: 2,
          id: 162359,
          known_for_department: "Acting",
          name: "Anil Raman",
          original_name: "Anil Raman",
          popularity: 2.899,
          profile_path: "/sZr3xh2h4xQ9xyiiQmvU3kkAzMo.jpg",
        },
        {
          character: "Mel Graham",
          credit_id: "57263cbb92514177820036a5",
          order: 57,
          adult: false,
          gender: 1,
          id: 173198,
          known_for_department: "Acting",
          name: "Heather Tom",
          original_name: "Heather Tom",
          popularity: 1.092,
          profile_path: "/pY8wGAMydRDVKDPlNaLOx7tWqrB.jpg",
        },
        {
          character: "Bouncer",
          credit_id: "5ec721b06c849200202c5038",
          order: 197,
          adult: false,
          gender: 2,
          id: 2573801,
          known_for_department: "Acting",
          name: "Benjamin Arcé",
          original_name: "Benjamin Arcé",
          popularity: 0.6,
          profile_path: "/wcGJcRKacrS5KaZ8k42XyA4zxNv.jpg",
        },
        {
          character: "Malcolm's Son",
          credit_id: "5ec7222dae2811001f3c66ef",
          order: 198,
          adult: false,
          gender: 2,
          id: 1476345,
          known_for_department: "Acting",
          name: "Aiden Finn",
          original_name: "Aiden Finn",
          popularity: 0.828,
          profile_path: "/AcFbLhKt16sPjwTZloVD6zX8ZXJ.jpg",
        },
        {
          character: "Klause",
          credit_id: "5ec7224d140bad001d19ec10",
          order: 199,
          adult: false,
          gender: 2,
          id: 1581107,
          known_for_department: "Acting",
          name: "Ash Lee",
          original_name: "Ash Lee",
          popularity: 1.045,
          profile_path: "/4utuaXs7Li4puP7TcdVwq9Owhyx.jpg",
        },
        {
          character: "Nikolas",
          credit_id: "5ec72372ae2811001e3ba128",
          order: 200,
          adult: false,
          gender: 2,
          id: 1392953,
          known_for_department: "Crew",
          name: "Yaroslav Poverlo",
          original_name: "Yaroslav Poverlo",
          popularity: 1.24,
          profile_path: "/cu8CjM5ZDpUkDaTi73XzwrUWxOU.jpg",
        },
        {
          character: "Assistant",
          credit_id: "5ec72c633d3557001eeeeee4",
          order: 201,
          adult: false,
          gender: 1,
          id: 1411570,
          known_for_department: "Acting",
          name: "Ashley Ross",
          original_name: "Ashley Ross",
          popularity: 1.4,
          profile_path: "/5Qw3cgRVM5J0xZimTmfD00RU2DL.jpg",
        },
        {
          character: "Bodyguard",
          credit_id: "5ec72e696c849200202c67b8",
          order: 202,
          adult: false,
          gender: 2,
          id: 1494866,
          known_for_department: "Acting",
          name: "Patrick Sparling",
          original_name: "Patrick Sparling",
          popularity: 0.6,
          profile_path: "/u1bPQgODoKXT2V0kE71nmsPqKvz.jpg",
        },
        {
          character: "Malcolm Graham",
          credit_id: "5ec7e7df0fb17f001d7ca915",
          order: 246,
          adult: false,
          gender: 2,
          id: 114000,
          known_for_department: "Acting",
          name: "Kevin Rankin",
          original_name: "Kevin Rankin",
          popularity: 6.07,
          profile_path: "/fOW5R6BSgRvMrt2R7KAxSk7L4H2.jpg",
        },
      ],
      id: 1160788,
      name: "Wingman",
      overview:
        "In attempt to find the contents of his stolen container, Lucifer enlists the help of an unlikely ally. Meanwhile, Chloe digs deeper into the Palmetto case, uncovering a lead that might finally expose the truth.",
      production_code: "4X6506",
      season_number: 1,
      still_path: "/3QkYv78ZlxYf54sLO71xYnoqzMr.jpg",
      vote_average: 7.7,
      vote_count: 36,
    },
    {
      air_date: "2016-03-14",
      episode_number: 8,
      crew: [
        {
          job: "Writer",
          department: "Writing",
          credit_id: "56c0b6abc3a36817fd00be48",
          adult: false,
          gender: 0,
          id: 1407158,
          known_for_department: "Writing",
          name: "Jenn Kao",
          original_name: "Jenn Kao",
          popularity: 0.6,
          profile_path: null,
        },
        {
          job: "Director",
          department: "Directing",
          credit_id: "56ff97a09251416783001aa1",
          adult: false,
          gender: 2,
          id: 205641,
          known_for_department: "Directing",
          name: "Eagle Egilsson",
          original_name: "Eagle Egilsson",
          popularity: 1.905,
          profile_path: null,
        },
      ],
      guest_stars: [
        {
          character: "Anthony Paolucci",
          credit_id: "56f28434c3a368077500125d",
          order: 28,
          adult: false,
          gender: 2,
          id: 58058,
          known_for_department: "Acting",
          name: "Lochlyn Munro",
          original_name: "Lochlyn Munro",
          popularity: 6.235,
          profile_path: "/bOJ03k0oe2R6snRgzV8M4Qtoo4O.jpg",
        },
        {
          character: "Richard Kester",
          credit_id: "56ff96bf925141677a001a11",
          order: 40,
          adult: false,
          gender: 2,
          id: 161932,
          known_for_department: "Acting",
          name: "Jim Rash",
          original_name: "Jim Rash",
          popularity: 6.727,
          profile_path: "/kCMBFCnPDcXgSonSgDUpZsJbQbT.jpg",
        },
        {
          character: "Dr. Jonathan Medina",
          credit_id: "56ff96d79251416776001b0f",
          order: 41,
          adult: false,
          gender: 2,
          id: 90534,
          known_for_department: "Acting",
          name: "Al Madrigal",
          original_name: "Al Madrigal",
          popularity: 2.388,
          profile_path: "/p4vN80EGGlzLb5J7G8Ss3n9K2pc.jpg",
        },
        {
          character: "Sandy Shaw",
          credit_id: "56ff9706c3a3686e88001b80",
          order: 42,
          adult: false,
          gender: 1,
          id: 185504,
          known_for_department: "Acting",
          name: "Joy Osmanski",
          original_name: "Joy Osmanski",
          popularity: 2.697,
          profile_path: "/xoRSO5b7hWN9i42fFEswHwStLEI.jpg",
        },
        {
          character: "Bystander",
          credit_id: "5ec72eee6c8492001f29b218",
          order: 203,
          adult: false,
          gender: 1,
          id: 1884551,
          known_for_department: "Acting",
          name: "Ese Atawo",
          original_name: "Ese Atawo",
          popularity: 2.253,
          profile_path: "/5rxs3gKeNgMbHfB0xjhSfWBuI4a.jpg",
        },
        {
          character: "Sexy Girl",
          credit_id: "5ec72f0aae2811001f3c7ea4",
          order: 204,
          adult: false,
          gender: 1,
          id: 2639816,
          known_for_department: "Acting",
          name: "Lia Farrelly-Hodge",
          original_name: "Lia Farrelly-Hodge",
          popularity: 1.96,
          profile_path: "/hSFu915cNsw6WEQIrpxTlgc3WhE.jpg",
        },
        {
          character: "Grieving Woman",
          credit_id: "5ec72f2bd2147c0022b9a206",
          order: 205,
          adult: false,
          gender: 1,
          id: 2300489,
          known_for_department: "Acting",
          name: "Jasmine Lukuku",
          original_name: "Jasmine Lukuku",
          popularity: 1.22,
          profile_path: "/dUf5gooYnFIKwo8iHOklXfkE1M5.jpg",
        },
        {
          character: "Hipster",
          credit_id: "5ec72f48ae281100203b052d",
          order: 206,
          adult: false,
          gender: 0,
          id: 1882898,
          known_for_department: "Acting",
          name: "James Paladino",
          original_name: "James Paladino",
          popularity: 0.84,
          profile_path: "/kaga96aDpAMuInkhJOLGPJXcvEf.jpg",
        },
        {
          character: "Tiffany",
          credit_id: "5ec72f72e635710020cd49f4",
          order: 208,
          adult: false,
          gender: 1,
          id: 2648374,
          known_for_department: "Acting",
          name: "Marisa Emma Smith",
          original_name: "Marisa Emma Smith",
          popularity: 0.98,
          profile_path: "/awGxfrDcRh3d03PINjJs8QliR8o.jpg",
        },
        {
          character: "Judge",
          credit_id: "5ec72f8b140bad001b1876c9",
          order: 209,
          adult: false,
          gender: 1,
          id: 65807,
          known_for_department: "Acting",
          name: "Ingrid Tesch",
          original_name: "Ingrid Tesch",
          popularity: 1.846,
          profile_path: "/qO8I8Xf0z9Vq21R0kvw7mDdRHSL.jpg",
        },
        {
          character: "Grieving Man",
          credit_id: "5ec72fda0fb17f001c7a4c36",
          order: 210,
          adult: false,
          gender: 2,
          id: 1727683,
          known_for_department: "Acting",
          name: "Adil Zaidi",
          original_name: "Adil Zaidi",
          popularity: 4.846,
          profile_path: "/ky0qSPdZzYdaThKgC8gE9YlINa5.jpg",
        },
        {
          character: "Party Girl",
          credit_id: "5ec72ff70fb17f001d7b7f8e",
          order: 211,
          adult: false,
          gender: 1,
          id: 1615066,
          known_for_department: "Acting",
          name: "Debs Howard",
          original_name: "Debs Howard",
          popularity: 4.305,
          profile_path: "/98Q0ZFr7MfgDWJr0aTD5M7Gb6MD.jpg",
        },
        {
          character: "Malcolm Graham",
          credit_id: "5ec7e7df0fb17f001d7ca915",
          order: 246,
          adult: false,
          gender: 2,
          id: 114000,
          known_for_department: "Acting",
          name: "Kevin Rankin",
          original_name: "Kevin Rankin",
          popularity: 6.07,
          profile_path: "/fOW5R6BSgRvMrt2R7KAxSk7L4H2.jpg",
        },
        {
          character: "Uni Cop",
          credit_id: "5ec72f60d2147c0023be77e8",
          order: 457,
          adult: false,
          gender: 2,
          id: 2648373,
          known_for_department: "Acting",
          name: "Todd Simmons",
          original_name: "Todd Simmons",
          popularity: 0.6,
          profile_path: null,
        },
      ],
      id: 1165518,
      name: "Et Tu, Doctor?",
      overview:
        "When a therapist is murdered, Lucifer and Chloe enlist the help of Dr. Linda to look into possible suspects. Meanwhile, Malcolm confronts Chloe about the night he was shot, and Lucifer experiences his first bout of jealousy.",
      production_code: "4X6507",
      season_number: 1,
      still_path: "/kCvPxVQ0OLyQG7VwPOzHTHGsbKV.jpg",
      vote_average: 7.2,
      vote_count: 35,
    },
    {
      air_date: "2016-03-21",
      episode_number: 9,
      crew: [
        {
          job: "Writer",
          department: "Writing",
          credit_id: "5700432ec3a3686e9200370c",
          adult: false,
          gender: 0,
          id: 1490537,
          known_for_department: "Writing",
          name: "Chris Rafferty",
          original_name: "Chris Rafferty",
          popularity: 0.84,
          profile_path: null,
        },
        {
          job: "Director",
          department: "Directing",
          credit_id: "5700434dc3a3686e92003711",
          adult: false,
          gender: 2,
          id: 1224779,
          known_for_department: "Directing",
          name: "David Frazee",
          original_name: "David Frazee",
          popularity: 1.96,
          profile_path: "/t6ofxu0y4jjpECFHihOQjpXBLjB.jpg",
        },
      ],
      guest_stars: [
        {
          character: "Father Frank Lawrence",
          credit_id: "570040a5c3a3680681000168",
          order: 43,
          adult: false,
          gender: 2,
          id: 91671,
          known_for_department: "Acting",
          name: "Colman Domingo",
          original_name: "Colman Domingo",
          popularity: 3.543,
          profile_path: "/2tu6T9ugnf82qIMGVKWSb0dvvq5.jpg",
        },
        {
          character: "Doyle Crain",
          credit_id: "570040b7c3a3680681000171",
          order: 44,
          adult: false,
          gender: 2,
          id: 1256070,
          known_for_department: "Acting",
          name: "Adam Bartley",
          original_name: "Adam Bartley",
          popularity: 2.373,
          profile_path: "/itPeAMCbQU2PU3QXJxEdC22oaov.jpg",
        },
        {
          character: "Connor",
          credit_id: "570040d19251417569000210",
          order: 45,
          adult: false,
          gender: 2,
          id: 1313633,
          known_for_department: "Acting",
          name: "Harrison Thomas",
          original_name: "Harrison Thomas",
          popularity: 2.051,
          profile_path: "/70oE9jaRLgkReir0SpIX9me7gjy.jpg",
        },
        {
          character: "Nikki",
          credit_id: "57004122c3a3686e7d003479",
          order: 46,
          adult: false,
          gender: 1,
          id: 1600095,
          known_for_department: "Acting",
          name: "Lisseth Chavez",
          original_name: "Lisseth Chavez",
          popularity: 3.921,
          profile_path: "/5QEONo0UPz7JrdKvGcAe3A6HPN9.jpg",
        },
        {
          character: "Mrs. Madison",
          credit_id: "5700426a9251416776003230",
          order: 47,
          adult: false,
          gender: 1,
          id: 92877,
          known_for_department: "Acting",
          name: "Catherine Kresge",
          original_name: "Catherine Kresge",
          popularity: 1.4,
          profile_path: "/r3vdczC0zGL3NyqfGY2M2MCafsB.jpg",
        },
        {
          character: "Brittanie #3",
          credit_id: "5ec7369d140bad001b188271",
          order: 212,
          adult: false,
          gender: 1,
          id: 2648410,
          known_for_department: "Acting",
          name: "Claire Fenech",
          original_name: "Claire Fenech",
          popularity: 1.96,
          profile_path: "/w64GBjh3pt37FGWiwgeab8KyqMP.jpg",
        },
        {
          character: "Pizza Guy",
          credit_id: "5ec738a16c8492001f29b7b6",
          order: 213,
          adult: false,
          gender: 2,
          id: 111930,
          known_for_department: "Acting",
          name: "Donnie MacNeil",
          original_name: "Donnie MacNeil",
          popularity: 4.202,
          profile_path: "/doX8E3XiNYOqDBUqUqBPCDShiCy.jpg",
        },
        {
          character: "Kid",
          credit_id: "5ec7391e8e2e00002124f185",
          order: 216,
          adult: false,
          gender: 2,
          id: 2648412,
          known_for_department: "Acting",
          name: "Jared Outten",
          original_name: "Jared Outten",
          popularity: 1.22,
          profile_path: "/foLdP2si60UYoeMPxhfNu5W3vTN.jpg",
        },
        {
          character: "Malcolm Graham",
          credit_id: "5ec7e7df0fb17f001d7ca915",
          order: 246,
          adult: false,
          gender: 2,
          id: 114000,
          known_for_department: "Acting",
          name: "Kevin Rankin",
          original_name: "Kevin Rankin",
          popularity: 6.07,
          profile_path: "/fOW5R6BSgRvMrt2R7KAxSk7L4H2.jpg",
        },
        {
          character: "Brittanie #2",
          credit_id: "5ec738bf8e2e0000201f4175",
          order: 732,
          adult: false,
          gender: 1,
          id: 1516211,
          known_for_department: "Acting",
          name: "Emily Maddison",
          original_name: "Emily Maddison",
          popularity: 4.532,
          profile_path: "/cGfJnsrslN75ju7Dpmv8NgyHDgI.jpg",
        },
        {
          character: "Brittanie #1",
          credit_id: "5ec7390e3d3557001ce8e5f6",
          order: 733,
          adult: false,
          gender: 1,
          id: 2648252,
          known_for_department: "Acting",
          name: "Tina Pham",
          original_name: "Tina Pham",
          popularity: 1.96,
          profile_path: "/sn7ycikKtANMU4TKJq98oHxNYpi.jpg",
        },
      ],
      id: 1165519,
      name: "A Priest Walks Into A Bar",
      overview:
        "A priest seeks out Lucifer's help when he suspects an underground drug operation has set up shop at a neighborhood youth center. Meanwhile, Malcolm manipulates a way to keep an eye on Dan.",
      production_code: "4X6508",
      season_number: 1,
      still_path: "/guWoA5SLNMVMo6J3vaZSMIEGyXh.jpg",
      vote_average: 8,
      vote_count: 34,
    },
    {
      air_date: "2016-03-28",
      episode_number: 10,
      crew: [
        {
          job: "Writer",
          department: "Writing",
          credit_id: "56f41101925141769e001e90",
          adult: false,
          gender: 0,
          id: 1382168,
          known_for_department: "Writing",
          name: "Alex Katsnelson",
          original_name: "Alex Katsnelson",
          popularity: 1.22,
          profile_path: null,
        },
        {
          job: "Writer",
          department: "Writing",
          credit_id: "5724ebc39251411d090002b0",
          adult: false,
          gender: 0,
          id: 1579755,
          known_for_department: "Writing",
          name: "Mike Costa",
          original_name: "Mike Costa",
          popularity: 1.4,
          profile_path: null,
        },
        {
          job: "Director",
          department: "Directing",
          credit_id: "5724ebfdc3a3685ac10008eb",
          adult: false,
          gender: 1,
          id: 1613214,
          known_for_department: "Directing",
          name: "Tara Nicole Weyr",
          original_name: "Tara Nicole Weyr",
          popularity: 1.38,
          profile_path: null,
        },
      ],
      guest_stars: [
        {
          character: "Junior Arias",
          credit_id: "56fb0af49251412883000145",
          order: 39,
          adult: false,
          gender: 2,
          id: 1182725,
          known_for_department: "Acting",
          name: "Manny Montana",
          original_name: "Manny Montana",
          popularity: 15.808,
          profile_path: "/seDWjQKEJx8fdOBgmMUw4TSyyTK.jpg",
        },
        {
          character: "Anne Martin",
          credit_id: "5724ea9d92514119ed002344",
          order: 47,
          adult: false,
          gender: 1,
          id: 72003,
          known_for_department: "Acting",
          name: "Tara Summers",
          original_name: "Tara Summers",
          popularity: 1.192,
          profile_path: "/4ZcoDTgcJWItPBkNAySyIfkAhCI.jpg",
        },
        {
          character: "Naomi Austen",
          credit_id: "5724eae9c3a368423a002385",
          order: 48,
          adult: false,
          gender: 1,
          id: 209038,
          known_for_department: "Acting",
          name: "Alessandra Torresani",
          original_name: "Alessandra Torresani",
          popularity: 8.604,
          profile_path: "/jR6VlKofhJhukFcSLQKXGO6kcls.jpg",
        },
        {
          character: "Young Hostess",
          credit_id: "594a80f192514145b900eb49",
          order: 77,
          adult: false,
          gender: 0,
          id: 1836857,
          known_for_department: "Acting",
          name: "Beatriz Brenes",
          original_name: "Beatriz Brenes",
          popularity: 1.099,
          profile_path: "/cs9oqkqsosuGhTEKPPIRDEGvBL2.jpg",
        },
        {
          character: "Officer",
          credit_id: "5ec74b92e635710021cc67d0",
          order: 217,
          adult: false,
          gender: 2,
          id: 1776683,
          known_for_department: "Acting",
          name: "David Chin",
          original_name: "David Chin",
          popularity: 1.116,
          profile_path: "/1mMTMkuLeKbGVufj3jSVsx4mvU0.jpg",
        },
        {
          character: "Cute Woman",
          credit_id: "5ec74bc6d2147c0022b9c70c",
          order: 218,
          adult: false,
          gender: 1,
          id: 1705590,
          known_for_department: "Acting",
          name: "Stefania Indelicato",
          original_name: "Stefania Indelicato",
          popularity: 1.4,
          profile_path: "/fHRNBd0XMPRyAnVlJvMGrBJXSv6.jpg",
        },
        {
          character: "Waitress",
          credit_id: "5ec74bf3ae2811001f3cb799",
          order: 219,
          adult: false,
          gender: 1,
          id: 1475808,
          known_for_department: "Acting",
          name: "Maddie Phillips",
          original_name: "Maddie Phillips",
          popularity: 7.273,
          profile_path: "/elKFVAsKVdD8oTArCr3zDxl2yR7.jpg",
        },
        {
          character: "Dishwasher",
          credit_id: "5ec74c4fae281100203b1cfd",
          order: 220,
          adult: false,
          gender: 0,
          id: 2366819,
          known_for_department: "Acting",
          name: "Jeff Reyes",
          original_name: "Jeff Reyes",
          popularity: 0.6,
          profile_path: "/pypE4ekPiI9qKOXchqR6EfLg0eK.jpg",
        },
        {
          character: "Malcolm Graham",
          credit_id: "5ec7e7df0fb17f001d7ca915",
          order: 246,
          adult: false,
          gender: 2,
          id: 114000,
          known_for_department: "Acting",
          name: "Kevin Rankin",
          original_name: "Kevin Rankin",
          popularity: 6.07,
          profile_path: "/fOW5R6BSgRvMrt2R7KAxSk7L4H2.jpg",
        },
        {
          character: "Penelope Decker",
          credit_id: "56f7c36bc3a3686a6e006bc8",
          order: 667,
          adult: false,
          gender: 1,
          id: 28412,
          known_for_department: "Acting",
          name: "Rebecca De Mornay",
          original_name: "Rebecca De Mornay",
          popularity: 8.511,
          profile_path: "/bGSvflCmfywasc3U8QAsJPaAek4.jpg",
        },
      ],
      id: 1165520,
      name: "Pops",
      overview:
        "Lucifer and Chloe are tasked with solving the murder of a prominent restaurateur. When they meet his son, they suspect he played a part in the death. Meanwhile, Chloe's mom returns home, sending Chloe's life into upheaval, as Lucifer learns his own dysfunctional family isn't nearly as unique as he thought.",
      production_code: "4X6509",
      season_number: 1,
      still_path: "/aqCLf3sbEvGQfLlKg1cYccu1hYK.jpg",
      vote_average: 7.5,
      vote_count: 30,
    },
    {
      air_date: "2016-04-11",
      episode_number: 11,
      crew: [
        {
          job: "Writer",
          department: "Writing",
          credit_id: "56f285139251415548001218",
          adult: false,
          gender: 1,
          id: 139853,
          known_for_department: "Writing",
          name: "Sheri Elwood",
          original_name: "Sheri Elwood",
          popularity: 1.22,
          profile_path: null,
        },
        {
          job: "Writer",
          department: "Writing",
          credit_id: "5725317dc3a368423a002c03",
          adult: false,
          gender: 2,
          id: 303599,
          known_for_department: "Writing",
          name: "David McMillan",
          original_name: "David McMillan",
          popularity: 0.694,
          profile_path: null,
        },
        {
          job: "Director",
          department: "Directing",
          credit_id: "5725323f9251417782000220",
          adult: false,
          gender: 1,
          id: 1400942,
          known_for_department: "Directing",
          name: "Mairzee Almas",
          original_name: "Mairzee Almas",
          popularity: 1.226,
          profile_path: "/wGOEgnJZtELk4SQpQEVFoMChAyl.jpg",
        },
      ],
      guest_stars: [
        {
          character: "Vanessa Dunlear",
          credit_id: "56f7c11d9251412cc00034b3",
          order: 36,
          adult: false,
          gender: 1,
          id: 1215689,
          known_for_department: "Acting",
          name: "Christina Chang",
          original_name: "Christina Chang",
          popularity: 17.287,
          profile_path: "/p1m4Da7ZOt6BOcXy4T58Mu3jAY3.jpg",
        },
        {
          character: "Will Flemming",
          credit_id: "57251970c3a36836a9000722",
          order: 49,
          adult: false,
          gender: 2,
          id: 26718,
          known_for_department: "Acting",
          name: "Dorian Missick",
          original_name: "Dorian Missick",
          popularity: 4.725,
          profile_path: "/n1Wsh7AZjsWcanQrTLwjZvGKw66.jpg",
        },
        {
          character: "Emmet Toussaint",
          credit_id: "57252fdfc3a3682d2400739d",
          order: 50,
          adult: false,
          gender: 2,
          id: 543524,
          known_for_department: "Acting",
          name: "Carlos Knight",
          original_name: "Carlos Knight",
          popularity: 1.777,
          profile_path: "/1ng8JRbsv4RL2d8eXCShHG4qoYS.jpg",
        },
        {
          character: "Kyle Erikson",
          credit_id: "57253023c3a368423a002bdd",
          order: 51,
          adult: false,
          gender: 2,
          id: 56676,
          known_for_department: "Acting",
          name: "Michael Welch",
          original_name: "Michael Welch",
          popularity: 7.456,
          profile_path: "/zx5GKHpBxYHY09ik818HTcJhu.jpg",
        },
        {
          character: "Louie Delgado",
          credit_id: "572530439251411e9f000b6a",
          order: 52,
          adult: false,
          gender: 2,
          id: 64670,
          known_for_department: "Acting",
          name: "Philip Granger",
          original_name: "Philip Granger",
          popularity: 1.317,
          profile_path: "/yUo0EbJlWnEl56cYXXkITVFbcVU.jpg",
        },
        {
          character: "Tim Dunlear",
          credit_id: "5ec74e738e2e0000201f6108",
          order: 221,
          adult: false,
          gender: 2,
          id: 1237734,
          known_for_department: "Acting",
          name: "Michasha Armstrong",
          original_name: "Michasha Armstrong",
          popularity: 2.696,
          profile_path: "/1nuX1dAXKer4F4k297yRaRGSw9H.jpg",
        },
        {
          character: "Gayle Sherman",
          credit_id: "5ec74e93140bad001b189e84",
          order: 222,
          adult: false,
          gender: 1,
          id: 157836,
          known_for_department: "Acting",
          name: "Julianne Christie",
          original_name: "Julianne Christie",
          popularity: 3.198,
          profile_path: "/hEiV9H8LIHe8VDqeTT8lqNs8awV.jpg",
        },
        {
          character: "Maitre D'",
          credit_id: "5ec751179979d2001f34f7a4",
          order: 223,
          adult: false,
          gender: 2,
          id: 1615071,
          known_for_department: "Acting",
          name: "Behtash Fazlali",
          original_name: "Behtash Fazlali",
          popularity: 0.6,
          profile_path: "/9A4sL503QrcnNA3vpurnXoBeabG.jpg",
        },
        {
          character: "Pianist (Musician)",
          credit_id: "5ec751eae635710022cecf55",
          order: 224,
          adult: false,
          gender: 1,
          id: 1988806,
          known_for_department: "Acting",
          name: "Giovanna Lin",
          original_name: "Giovanna Lin",
          popularity: 0.98,
          profile_path: "/4bgd3F9YAFtcCxz6m2kHf7dofBt.jpg",
        },
        {
          character: "Hot Lonely / Kelly Dolman",
          credit_id: "5ec75221d2147c0021b6724c",
          order: 225,
          adult: false,
          gender: 1,
          id: 46902,
          known_for_department: "Acting",
          name: "Kirsten Robek",
          original_name: "Kirsten Robek",
          popularity: 7.967,
          profile_path: "/iqcerFwPYnWjoTu3jgs38PDUuqJ.jpg",
        },
        {
          character: "Malcolm Graham",
          credit_id: "5ec7e7df0fb17f001d7ca915",
          order: 246,
          adult: false,
          gender: 2,
          id: 114000,
          known_for_department: "Acting",
          name: "Kevin Rankin",
          original_name: "Kevin Rankin",
          popularity: 6.07,
          profile_path: "/fOW5R6BSgRvMrt2R7KAxSk7L4H2.jpg",
        },
      ],
      id: 1165521,
      name: "St. Lucifer",
      overview:
        "When philanthropist Tim Dunlear is found dead, Lucifer explores his good side by becoming a benefactor for Tim’s glitzy Los Angeles charity.",
      production_code: "4X6511",
      season_number: 1,
      still_path: "/m0EeNM6XyMb2gMKF1b6vyFoaTND.jpg",
      vote_average: 7.9,
      vote_count: 29,
    },
    {
      air_date: "2016-04-18",
      episode_number: 12,
      crew: [
        {
          job: "Writer",
          department: "Writing",
          credit_id: "56f16d58c3a36850a700002b",
          adult: false,
          gender: 1,
          id: 1222590,
          known_for_department: "Writing",
          name: "Ildy Modrovich",
          original_name: "Ildy Modrovich",
          popularity: 0.978,
          profile_path: null,
        },
        {
          job: "Director",
          department: "Directing",
          credit_id: "5726288ac3a3683841002270",
          adult: false,
          gender: 2,
          id: 17309,
          known_for_department: "Directing",
          name: "Greg Beeman",
          original_name: "Greg Beeman",
          popularity: 2.188,
          profile_path: "/tIcHT5LMR5x7AXDU8YewY660m33.jpg",
        },
      ],
      guest_stars: [
        {
          character: "Jacob Williams",
          credit_id: "572626dd925141774400343a",
          order: 53,
          adult: false,
          gender: 2,
          id: 169349,
          known_for_department: "Acting",
          name: "Evan Arnold",
          original_name: "Evan Arnold",
          popularity: 1.661,
          profile_path: "/meFpF2hqoODL1TMNgx1MNqUWiC1.jpg",
        },
        {
          character: "Mitch 'Onyx' Watson",
          credit_id: "572626efc3a368384100223e",
          order: 54,
          adult: false,
          gender: 2,
          id: 56366,
          known_for_department: "Acting",
          name: "Ross McCall",
          original_name: "Ross McCall",
          popularity: 5.631,
          profile_path: "/6l3lARiyHHISOIntSlvYv0JgTHz.jpg",
        },
        {
          character: "Rose",
          credit_id: "5726270092514119ed005d18",
          order: 55,
          adult: false,
          gender: 1,
          id: 1197119,
          known_for_department: "Acting",
          name: "Sarah Grey",
          original_name: "Sarah Grey",
          popularity: 3.594,
          profile_path: "/7XNAITcdppSo0TA1VqOw6PzgFfg.jpg",
        },
        {
          character: "Mr. Davis",
          credit_id: "572627c492514177820033fd",
          order: 56,
          adult: false,
          gender: 2,
          id: 102748,
          known_for_department: "Acting",
          name: "Andrew Wheeler",
          original_name: "Andrew Wheeler",
          popularity: 2.878,
          profile_path: "/bevGraSMlYp5HMu6pD7O9JDyP7l.jpg",
        },
        {
          character: "Follower",
          credit_id: "5ec7607a140bad001d1a55c7",
          order: 226,
          adult: false,
          gender: 1,
          id: 1683867,
          known_for_department: "Acting",
          name: "Karishma Ahluwalia",
          original_name: "Karishma Ahluwalia",
          popularity: 2.27,
          profile_path: "/jKYECcYRmz5bNDSVpSMOfu8eYy3.jpg",
        },
        {
          character: "Corazon",
          credit_id: "5ec767fc6c849200212b4083",
          order: 230,
          adult: false,
          gender: 2,
          id: 1459526,
          known_for_department: "Acting",
          name: "Ryan Bruce",
          original_name: "Ryan Bruce",
          popularity: 2.231,
          profile_path: "/yVf2MbXAXkptW5LAiTSXg9Bgm57.jpg",
        },
        {
          character: "Satanist #2",
          credit_id: "5ec7d8016c849200212bbc28",
          order: 231,
          adult: false,
          gender: 1,
          id: 2649171,
          known_for_department: "Acting",
          name: "Erin Cameron",
          original_name: "Erin Cameron",
          popularity: 0.6,
          profile_path: "/pFcnP8xPRswnwD2YTanVmhFq2Yu.jpg",
        },
        {
          character: "Satanist #3",
          credit_id: "5ec7d905140bad001b192db5",
          order: 232,
          adult: false,
          gender: 2,
          id: 1920739,
          known_for_department: "Acting",
          name: "Ryan Elm",
          original_name: "Ryan Elm",
          popularity: 1.96,
          profile_path: "/tbHvR855wPKbepa1dtLAh06uCXg.jpg",
        },
        {
          character: "Tattoo Artist",
          credit_id: "5ec7d928d2147c0022ba5ba9",
          order: 233,
          adult: false,
          gender: 1,
          id: 2649191,
          known_for_department: "Acting",
          name: "Kristin Kowalski",
          original_name: "Kristin Kowalski",
          popularity: 1.96,
          profile_path: "/xkffR5A8peIWKQl8bNc5AgEKRDt.jpg",
        },
        {
          character: "Female Detective",
          credit_id: "5ec7dd9ee24b930021d4d6a7",
          order: 234,
          adult: false,
          gender: 0,
          id: 1475106,
          known_for_department: "Acting",
          name: "Danielle Kremeniuk",
          original_name: "Danielle Kremeniuk",
          popularity: 1.4,
          profile_path: "/2Y2jkqTSdR0oxufv74wCftY78Bh.jpg",
        },
        {
          character: "Satanist #1",
          credit_id: "5ec7de8b140bad001b193447",
          order: 235,
          adult: false,
          gender: 2,
          id: 2649210,
          known_for_department: "Acting",
          name: "Aaron Post",
          original_name: "Aaron Post",
          popularity: 0.6,
          profile_path: "/u5bXkhUDreZsAM20ilBBus1Q5DP.jpg",
        },
        {
          character: "Uni Cop",
          credit_id: "5ec7e01fe635710022cfb2ea",
          order: 236,
          adult: false,
          gender: 0,
          id: 1685448,
          known_for_department: "Acting",
          name: "Teana-Marie Smith",
          original_name: "Teana-Marie Smith",
          popularity: 3.137,
          profile_path: "/fcQjfVZjqUbIubL23bPPht1XVAm.jpg",
        },
        {
          character: "Malcolm Graham",
          credit_id: "5ec7e7df0fb17f001d7ca915",
          order: 246,
          adult: false,
          gender: 2,
          id: 114000,
          known_for_department: "Acting",
          name: "Kevin Rankin",
          original_name: "Kevin Rankin",
          popularity: 6.07,
          profile_path: "/fOW5R6BSgRvMrt2R7KAxSk7L4H2.jpg",
        },
        {
          character: "Newscaster",
          credit_id: "5ec7642e8e2e0000201f79f6",
          order: 490,
          adult: false,
          gender: 1,
          id: 2129177,
          known_for_department: "Acting",
          name: "Sonia Beeksma",
          original_name: "Sonia Beeksma",
          popularity: 1.099,
          profile_path: "/p6KgG87uCb0oZF8XApBhRs2zS57.jpg",
        },
        {
          character: "Uniformed Officer",
          credit_id: "5f3fc9b319ab590035208cab",
          order: 689,
          adult: false,
          gender: 2,
          id: 1757341,
          known_for_department: "Acting",
          name: "Andrew Baker",
          original_name: "Andrew Baker",
          popularity: 1.96,
          profile_path: "/55tQFXFBXtKGTub9N1dF54TCm1C.jpg",
        },
        {
          character: "Uniformed Officer",
          credit_id: "5ec947cfa35c8e0020e27118",
          order: 690,
          adult: false,
          gender: 0,
          id: 2602293,
          known_for_department: "Acting",
          name: "Jorden Birch",
          original_name: "Jorden Birch",
          popularity: 1.62,
          profile_path: "/h9FehQZPTnoo9bs82ao13l9ctDC.jpg",
        },
      ],
      id: 1165522,
      name: "#TeamLucifer",
      overview:
        "When a woman is found dead on the Hollywood Walk of Fame - with her body twisted into the shape of a pentagram - the investigation leads Lucifer and team into the world of Satanists, where they soon realize, evil doesn't always live where we expect it to.",
      production_code: "4X6512",
      season_number: 1,
      still_path: "/jycEjP6R7cd23FasOdNp61d8Xk1.jpg",
      vote_average: 8.1,
      vote_count: 29,
    },
    {
      air_date: "2016-04-25",
      episode_number: 13,
      crew: [
        {
          job: "Director",
          department: "Directing",
          credit_id: "56be64919251417344004abb",
          adult: false,
          gender: 2,
          id: 11817,
          known_for_department: "Directing",
          name: "Nathan Hope",
          original_name: "Nathan Hope",
          popularity: 2.088,
          profile_path: null,
        },
        {
          job: "Writer",
          department: "Writing",
          credit_id: "56be64789251417356004c46",
          adult: false,
          gender: 2,
          id: 1248201,
          known_for_department: "Writing",
          name: "Joe Henderson",
          original_name: "Joe Henderson",
          popularity: 1.96,
          profile_path: null,
        },
      ],
      guest_stars: [
        {
          character: "Mel Graham",
          credit_id: "57263cbb92514177820036a5",
          order: 57,
          adult: false,
          gender: 1,
          id: 173198,
          known_for_department: "Acting",
          name: "Heather Tom",
          original_name: "Heather Tom",
          popularity: 1.092,
          profile_path: "/pY8wGAMydRDVKDPlNaLOx7tWqrB.jpg",
        },
        {
          character: "Jason",
          credit_id: "57263ce3c3a3685899003088",
          order: 58,
          adult: false,
          gender: 2,
          id: 173977,
          known_for_department: "Acting",
          name: "Steven Lee Allen",
          original_name: "Steven Lee Allen",
          popularity: 1.214,
          profile_path: "/1sm9vVnCa5aUbMsn7JwJhVO8gsK.jpg",
        },
        {
          character: "Desk Cop",
          credit_id: "5ec7e1816c849200202d90bb",
          order: 237,
          adult: false,
          gender: 2,
          id: 1530465,
          known_for_department: "Acting",
          name: "Ben Afful",
          original_name: "Ben Afful",
          popularity: 0.98,
          profile_path: "/c20LLqPt4aefFvDC3Ldezp8jHVQ.jpg",
        },
        {
          character: "Neil Palmer",
          credit_id: "5ec7e1f0140bad001b193906",
          order: 240,
          adult: false,
          gender: 2,
          id: 2848,
          known_for_department: "Acting",
          name: "Craig Erickson",
          original_name: "Craig Erickson",
          popularity: 1.614,
          profile_path: "/5NOIVaJSY8nNxmxHR35pKj5WDXG.jpg",
        },
        {
          character: "Widow",
          credit_id: "5ec7e269e635710020ce2191",
          order: 241,
          adult: false,
          gender: 1,
          id: 2649228,
          known_for_department: "Acting",
          name: "Ashley Evans",
          original_name: "Ashley Evans",
          popularity: 0.6,
          profile_path: "/2fqkvlhpudJ5OiMznyGMmXo7TEw.jpg",
        },
        {
          character: "Jackson",
          credit_id: "5ec7e506e24b930021d4e0c9",
          order: 243,
          adult: false,
          gender: 2,
          id: 106951,
          known_for_department: "Acting",
          name: "Paul Lazenby",
          original_name: "Paul Lazenby",
          popularity: 1.243,
          profile_path: "/3J4xzfU545NROfNuTUmXrTbapeg.jpg",
        },
        {
          character: "Tommy",
          credit_id: "5ec7e529e635710022cfbb6c",
          order: 244,
          adult: false,
          gender: 2,
          id: 169467,
          known_for_department: "Acting",
          name: "Danny Wattley",
          original_name: "Danny Wattley",
          popularity: 1.242,
          profile_path: "/aHh87mAQpdacOLnxvwfDJWvayAu.jpg",
        },
        {
          character: "Malcolm Graham",
          credit_id: "5ec7e7df0fb17f001d7ca915",
          order: 246,
          adult: false,
          gender: 2,
          id: 114000,
          known_for_department: "Acting",
          name: "Kevin Rankin",
          original_name: "Kevin Rankin",
          popularity: 6.07,
          profile_path: "/fOW5R6BSgRvMrt2R7KAxSk7L4H2.jpg",
        },
        {
          character: "Uniformed Officer",
          credit_id: "5f3fc9b319ab590035208cab",
          order: 689,
          adult: false,
          gender: 2,
          id: 1757341,
          known_for_department: "Acting",
          name: "Andrew Baker",
          original_name: "Andrew Baker",
          popularity: 1.96,
          profile_path: "/55tQFXFBXtKGTub9N1dF54TCm1C.jpg",
        },
        {
          character: "Uniformed Officer",
          credit_id: "5ec947cfa35c8e0020e27118",
          order: 690,
          adult: false,
          gender: 0,
          id: 2602293,
          known_for_department: "Acting",
          name: "Jorden Birch",
          original_name: "Jorden Birch",
          popularity: 1.62,
          profile_path: "/h9FehQZPTnoo9bs82ao13l9ctDC.jpg",
        },
        {
          character: "Uniformed Officer",
          credit_id: "5ec7e3bf9979d200213a31d3",
          order: 710,
          adult: false,
          gender: 2,
          id: 1366658,
          known_for_department: "Acting",
          name: "Devielle Johnson",
          original_name: "Devielle Johnson",
          popularity: 1.633,
          profile_path: "/aLTVHMv4EMniPAXXzMmDoItCLvi.jpg",
        },
      ],
      id: 1186049,
      name: "Take Me Back To Hell",
      overview:
        "When Lucifer is framed for murder, he and Chloe must work together to clear his name and prove the identity of the true killer.",
      production_code: "4X6513",
      season_number: 1,
      still_path: "/fUOlgpJgR9GBHBvLqad0zZUk0aO.jpg",
      vote_average: 8.2,
      vote_count: 30,
    },
  ],
  name: "Season 1",
  overview:
    "Bored with being the Lord of Hell, the devil relocates to Los Angeles, where he opens a nightclub and forms a connection with a homicide detective.",
  id: 68415,
  poster_path: "/9qvNXKYqZEsYn3g3yn5tXQe0ceB.jpg",
  season_number: 1,
};
